version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/extratravel?schema=public
      - JWT_SECRET=supersecretjwtkey_extratravelpoint_2026
      - QR_SECRET=supersecretqrkey_hmac_2026
    depends_on:
      - postgres
      - redis

  admin-panel:
    build: ./admin-panel
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api/v1
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    container_name: extratravel_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: extratravel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: extratravel_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
